### ISSUE TITLE
Add stress tests and find the recommended strategy for memory stability

### ISSUE THREAD

**Issue by mathetake** [tetratelabs/proxy-wasm-go-sdk#109]
e.g. executing `runtime.GC` in `OnTick`

**Comment by mathetake** [comment]
hey @musaprg can you give the timeline here, and what's your progress? It is ok to give up but being silent is the worst I think.

**Comment by musaprg** [comment]
@mathetake I'm sorry for the late. I was trying several libraries and chose fortio/fortio to use for our e2e load testing because it was handier than others and can be used as a go library. I am writing the test scenario based on the previous (already solved) issue https://github.com/envoyproxy/envoy/issues/14856. The small case (the payload size = 128KB, QPS = 10000) works fine, but the test with target case (the payload size = 32MB, QPS = 10000) isn't over. I'm investigating why this occurs.
