### ISSUE TITLE
gRPC callouts support

### ISSUE THREAD

**Issue by mathetake** [tetratelabs/proxy-wasm-go-sdk#14]

**Comment by mathetake** [comment]
https://github.com/tetratelabs/getenvoy/issues/101

**Comment by mathetake** [comment]
Given that this is going to be a lot of work and the spec is unstable, work on this later

**Comment by rfyiamcool** [comment]
👍

**Comment by chrisjpalmer** [comment]
Hello just wondering if there has been any updates on this one? At work we use istio and are looking to make calls to a GRPC service that can answer auth questions. The most ideal would be to use GRPC for this. However if its a while off, perhaps the next best thing is http? My understanding is that GRPC would be more efficient because it maintains one active connection per host as opposed to http2 which will eventually retire connections.

Thank you!

**Comment by mathetake** [comment]
This really depends on the upstream work in TinyGo: https://github.com/tinygo-org/tinygo/issues/1879 stay tuned!

**Comment by gedw99** [comment]
@mathetake thanks for raising this as I have been looking for a viable option for using GRPC and GRPC web 

GRPC web with WASM in browsers
GRPC with envoy proxy WASI .

**Comment by zd9KgA** [comment]
Hi @mathetake!

Just like @gedw99, I'd like to be able to make gRPC calls (e.g., to update permissions in https://github.com/authzed/spicedb) from a custom envoy filter written using this SDK. (The envoy `ext_authz` filter provides no option to process the response.)

Would you suggest to wait for progress here?

**Comment by mathetake** [comment]
https://github.com/tetratelabs/proxy-wasm-go-sdk/pull/451
