### ISSUE TITLE
How to route request to another backend api? #148

### ISSUE THREAD

**Issue by SMakhrov** [tetratelabs/proxy-wasm-go-sdk#149]
I have wasm filter which proxies to 
    - name: staticreply
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 8099

by default.

Is there a way to change target backend api on fly, for example to 127.0.0.1:8100:

    - name: staticreply
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 8100

???

**Comment by mathetake** [comment]
this sounds more of an Envoy question rather than Proxy-Wasm. In general, we could do the routing stuff based on headers in the rouer: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/route_matching

so the only thing you need to do is configure routing (which is pure Envoy side configuration) and doing header manipulation in Proxy-Wasm plugins (use `SetHttpRequestHeader` API).

**Comment by SMakhrov** [comment]
I've tried this, but doesn't work:
`			err := proxywasm.SetHttpRequestHeader("host", "localhost:8098")
			proxywasm.LogInfof("Try to route to canary service")
			if err != nil {
				proxywasm.LogCritical("failed to set request header: host")
			}
`
And you're speaking about external routing with full hosts. But I want to route inside kubernetes to another service.
