### ISSUE TITLE
Changing request route to another backend api doesn't work

### ISSUE THREAD

**Issue by SMakhrov** [tetratelabs/proxy-wasm-go-sdk#157]
Due to no answers in this ticket https://github.com/tetratelabs/proxy-wasm-go-sdk/issues/149 and at discussion: https://github.com/tetratelabs/proxy-wasm-go-sdk/discussions/148 I had to up this problem again.

**Problem definition:**
I want to change backend api address from localhost:8099 (web_service) to localhost:8100 (web_service_canary). 

**What was ​tried:**
According to tip from https://github.com/tetratelabs/proxy-wasm-go-sdk/issues/149 I have tried to use header :authority. But it doesn't work.

My code is presented here:
https://github.com/SMakhrov/proxy-wasm-go-sdk/tree/dev/feature/example_change_authority/examples/change_authority

For run use:
```
make build.example name=change_authority && make run name=change_authority
curl http://localhost:18000
```

Please help anyone.

**Comment by mathetake** [comment]
As I sadi, this is more about Envoy configuration rather than SDK nor Proxy-Wasm at all. You'd better learn Envoy basic before dive deeper into Wasm world which is highly advanced field. 

Having said that, I added the example in https://github.com/tetratelabs/proxy-wasm-go-sdk/pull/160  so I could save others like you in the future. Thanks!

**Comment by SMakhrov** [comment]
@mathetake thank you so much!!! I will try your example.
