### ISSUE TITLE
ResumeHttpRequest() and return types.ActionPause works only once

### ISSUE THREAD

**Issue by SMakhrov** [tetratelabs/proxy-wasm-go-sdk#158]
Steps to reproduce
1. Do proxywasm.DispatchHttpCall in OnHttpRequestHeaders.
2. At OnHttpRequestHeaders return types.ActionPause. It will waits resuming.
3. Call proxywasm.ResumeHttpRequest() at callback
4. Do proxywasm.DispatchHttpCall in OnHttpRequestBody.
5. At OnHttpRequestBody return types.ActionPause. 

Expected:
After step 5 OnHttpRequestBody will be paused

Actual:
After step 5 OnHttpRequestBody will continued

Problem definition. If we call ResumeHttpRequest() once, then it will enabled in all others On Request functions and Pause will not work

**Comment by mathetake** [comment]
Please provide the more detailed information as I said in #159  SDK, Envoy version, and the example code.

**Comment by SMakhrov** [comment]
@mathetake, I've prepared example: https://github.com/SMakhrov/proxy-wasm-go-sdk/tree/dev/feature/example_change_authority/examples/second_pause_dont_work

Please use this for make and run:
```
 make build.example name=second_pause_dont_work && make run name=second_pause_dont_work
```
then 
```
curl --request GET \
  --url http://localhost:18000/ \
  --header 'Content-Type: application/json' \
  --data '{
	"name": "test"
}'
```

You will see that second pause at OnHttpRequestBody will not work.

**Comment by mathetake** [comment]
Thanks for putting them. I will look into in a few weeks since I'm going into a Japan's holiday season😄 Thanks!

**Comment by SMakhrov** [comment]
Thank you, @mathetake ! :) I will be waiting your help! :) Happy holidays ;)

**Comment by mathetake** [comment]
OK this behavior is expected since you already continues the headers in the first callback which results in sending request headers to the upstream. So there's no way for you to stop headers from onRequestBody no matter which status it returns. 
Note that the response you receive depends on which response (from upstream or from local response in callback passed in onRequestBody) is handled by Envoy first. See what happens remove `DispatchHttpCall` and make OnHttpRequestHeades return `Continue`.

Closing now.
