### ISSUE TITLE
Panics in call DispatchHttpCall inside the callback of DispatchHttpCall.

### ISSUE THREAD

**Issue by SMakhrov** [tetratelabs/proxy-wasm-go-sdk#159]
When I'm trying to call DispatchHttpCall inside DispatchHttpCall I see error:
`wasm log my_root_id: panic: runtime error: nil pointer dereference
Function: proxy_on_http_call_response failed: Uncaught RuntimeError: unreachable
Proxy-Wasm plugin in-VM backtrace:
  0:  0xadb - runtime.runtimePanic
  1:  0xb23 - runtime.nilPanic
  2:  0x10e3b - github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm.DispatchHttpCall
  3:  0x130dc - proxy_on_http_call_response`

**Comment by mathetake** [comment]
@SMakhrov hey,  please provide more details information for **EVERY** issue you make.  Do you really think that all the error/issue/question you report is applicable to every versions of Envoy and every version of SDK? Keep in mind that open source doesn't mean you can get any support for free, and should be crystal clear about the thing you have to solve in order to reduce the cost all the maintainers incur by doing back and forth with users. This is voluntary work. Plus, can you use "```" to make your comment cleaned up??

Provide version of Envoy, this SDK and your code to reproduce the behavior. 

Please note that this should work as I tested locally. So until you could reproduce this with the latest SDK and Envoy and provide the code, I'm closing this.

**Comment by SMakhrov** [comment]
@mathetake, I've prepared example for this case too: https://github.com/SMakhrov/proxy-wasm-go-sdk/tree/dev/feature/example_change_authority/examples/second_pause_dont_work

Please use this for make and run:
```
make build.example name=twice_httpcall && make run name=twice_httpcall
```
then 
```
curl --request GET \
  --url http://localhost:18000/ \
  --header 'Content-Type: application/json' \
  --data '{
	"name": "test"
}'
```

Expected behaviour:
DispatchHttpCall correcly calls inside another DispatchHttpCall

Actual behaviour:
Panics error


```
envoy  version: d362e791eb9e4efa8d87f6d878740e72dc8330ac/1.18.2/clean-getenvoy-76c310e-envoy/RELEASE/BoringSSL
tinygo version 0.17.0 linux/amd64 (using go version go1.16.3 and LLVM version 11.0.0)
```

SDK was added as import 
```
import (
	"github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm"
	"github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm/types"
)
```
