### ISSUE TITLE
Request properties in proxytest

### ISSUE THREAD

**Issue by anuraaga** [tetratelabs/proxy-wasm-go-sdk#323]
Currently, it seems proxytest does not support `proxywasm.GetProperty`. 

Would it make sense to have a `SetProperty(contextID uint32, key []string, val []byte)` on the host emulator?

https://github.com/tetratelabs/proxy-wasm-go-sdk/blob/main/proxywasm/proxytest/http.go#L360

/cc @mathetake

**Comment by anuraaga** [comment]
For reference, I am using `GetProperty` in the plugin here

https://github.com/anuraaga/coraza-wasm-filter/pull/15/files#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261R175

**Comment by mathetake** [comment]
I would like to support, but the problem is that semantics of property_get/set are extremely complex... Even I don't get the whole behavior like when the struct is serialized as protobuf, and when it is serialized as the proxy-wasm specific list, etc. Eg https://github.com/tetratelabs/proxy-wasm-go-sdk/issues/284

https://github.com/envoyproxy/envoy/blob/main/source/extensions/common/wasm/context.cc#L596

I think we should start with the basic type (int, string)?

**Comment by anuraaga** [comment]
I think that is the logic to resolve the path expression within the proxy. But for test, we just want to set a fixed value that is accessible from the host. Since the ABI accepts strings for path and returns bytes value, isn't that enough without worrying about types?

**Comment by anuraaga** [comment]
Duplicate of #250
